##
# Copyright 2021 Kenta Ishii
# License: 3-Clause BSD License
# SPDX Short Identifier: BSD-3-Clause
##

# Name of Program
NAME := sequencer_serial_uart

# Calibration of Internal RC Oscillator for Individual Difference, Operating Voltage, and Temperature
CALIB_VALUE := -0x04

# Unprogrammed CKDIV8, Internal PLL 16.0MHz Clock
LFUSE := 0xE1

include ../attiny85.mk
