##
# Copyright 2021 Kenta Ishii
# License: 3-Clause BSD License
# SPDX Short Identifier: BSD-3-Clause
##

# Name of Program
NAME := blinker

# Calibration of Internal RC Oscillator for Individual Difference, Operating Voltage, and Temperature
CALIB_VALUE := -0x04

include ../attiny85.mk
